# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: QasimK
email: noreply@IAmQasimK.com
description: "Yet Another Blog, But This One Is Mine"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://IAmQasimK.com" # the base hostname & protocol for your site, e.g. http://example.com
githubCommentsUrlPrefix: "https://github.com/QasimK/qasimk.github.io/issues/"
author:
  name: QasimK
  github:  QasimK
  twitter: IAmQasimK

# jekyll-seo-tag
logo: /favicon-128.png

# Build settings
gems:
  - jekyll-seo-tag
  - jekyll-feed
permalink: pretty
markdown: kramdown
include:
  - _pages
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
