# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.
# Site settings, accessibly as {{ site.title }}.
# You can create any custom variable you would like: {{ site.my_variable }}.

title: QasimK
url: "https://QasimK.io"  # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""  # the subpath of your site, e.g. /blog
timezone: Europe/London

# Collections
collections_dir: collections
collections:
  talks:
    output: true
    permalink: /:collection/:year/:title/
  comments:
    output: true
    permalink: /:collection/:year/:title/

# Custom variables
githubCommentsUrlPrefix: "https://github.com/QasimK/qasimk.github.io/discussions/"

# jekyll-seo-tag
tagline: "Yet Another Blog, But This One Is Mine"
logo: /favicon-32x32.png
locale: en_GB

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
permalink: /:categories/:year/:title/
markdown: kramdown
include:
  - _pages
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
